### ISSUE TITLE
PyPI is out of date.

### ISSUE THREAD

**Issue by edthedev** [JustinAzoff/bhr-client#10]
[The version of BHR Client published on PyPI is from 2017][1]. This causes out of date installs when installing i.e. https://github.com/ncsa/bhr-client-exabgp - which itself looks in PyPI for `bhr-client`.

[1]: https://pypi.org/project/bhr-client/#history

If there's interest, my team would be glad to collaborate on setting up a new GitHub workflow to automatically publish new versions of BHR client to PyPI. We recently set this up for our `AWC CLI Login` plugin.

Our workflow example starts here: 
https://github.com/techservicesillinois/awscli-login/blob/7fea4f9f6e879cd7bee7710c941fd58292c92f56/.github/workflows/cicd.yml#L143

and the relevant command is here:
https://github.com/techservicesillinois/awscli-login/blob/7fea4f9f6e879cd7bee7710c941fd58292c92f56/.github/workflows/cicd.yml#L181

**Comment by JustinAzoff** [comment]
ah, I forgot I had ever published it there.  I can see about publishing the latest version, but github action would definitely help here.

**Comment by JustinAzoff** [comment]
pushed the latest version to pypi

**Comment by edthedev** [comment]
Thanks @JustinAzoff
